### ISSUE TITLE
IINACT & Browsingway: Cactbot overlays won't activate & IINACT optimizations option not working

### ISSUE THREAD

**Issue by jtabox** [Styr1x/Browsingway#38]
I'm not really sure if it's an issue with IINACT or with Browsingway, but Cactbot overlays won't activate automatically when they should. For example the raidboss module won't start showing its warnings for the first boss in each dungeon, unless I go to Browsingway settings and manually reload every overlay individually. Then they work but need to be reloaded every time I enter a dungeon. Same thing happens with the radar module, it's supposed to pick up the various hunt marks in the open world, but it won't unless I manually reload it.
Also, clicking ACT/IINACT optimizations in Browsingway settings disables the various overlays completely, they never show even though IINACT is running. I have to keep this option disabled to have the overlays showing up and working.

**Comment by Styr1x** [comment]
IINACT recently changed to being a Dalamud plugin. The ACT optimizations don't reflect that, so that option needs to be inchecked for IINACT running as a plugin.
The behavior you have is expected, because IINACT loads / is ready after Browsingway, so your overlays don't work in that case unless reloaded.

I'll reach out to the IINACT author for adding support to the plugin
