### ISSUE TITLE
Heavy stuttering on 2560x1440 (144hz) resolution

### ISSUE THREAD

**Issue by IChupaI** [Styr1x/Browsingway#43]
At this time the process "Browsingway.Renderer.exe" loads the CPU heavily.
Stuttering stops when dalamud window is open or game window is unfocused.
1920x1080 (144hz) works fine

**Comment by Styr1x** [comment]
I'm running it on 4k 144hz and have no issue;
Browsingway.Renderer.exe is the process that runs CEF - no code in it was changed, but I had to update CEF itself because of the security vulnerabilities.

I had a person with an odd CEF issue in the past that went away after updating it, but Browsingway already uses the latest CEF version available.

Is anything related to Browsingway inside your Dalamud.log?
Are you by any chance on a Windows version older than 10?

**Comment by wfournier** [comment]
Had a similar issue at 4K 144hz. I noticed that the overlay was fine when it first appears in the character select screen, but it slowed to a crawl as soon as I got in game. I found that disabling G-Sync solved the issue. This was in borderless fullscreen, but I honestly don't know if that's related.

**Comment by IChupaI** [comment]
> Had a similar issue at 4K 144hz. I noticed that the overlay was fine when it first appears on the main menu, but it slowed to a crawl as soon as I got in game. I found that disabling G-Sync solved the issue. This was in borderless fullscreen, but I honestly don't know if that's related.
> 
> Edit: When you say stuttering, do you mean the whole game is or only the overlay? Because in my case only the overlay was acting weird.

I mean overlay, yes.
It looks like the problem is really in G SYNC. After I disabled it in the NVIDIA Control Panel, the overlay worked fine. But the overlay also started working well after re-enabling G SYNC.
After rebooting the PC, the problem returned, but this time ALT+TAB solved it.
This appeared after the last update.
The problem existed before, but it resolved itself very quickly and I did not pay attention to it.

My spec:
Win 10 x64
Monitor - Gigabyte G27Q
GPU - GTX 1070
CPU - i7-6700
